### ISSUE TITLE
[bug/issues report] Current running issues

### ISSUE THREAD

**Issue by JourneyOver** [campanflaviu/plexius#1]
Just throwing in the few issues/bugs that are currently happening as of version 1.2

- The show Time after Time (2017) is grabbing the wrong IMDB for both show and season and episode.

> It's grabbing it's rating from http://www.imdb.com/title/tt0108960/ and the season is grabbing it's rating from http://www.imdb.com/title/tt5348406/ (I don't understand that one since IMDB doesn't have ratings for seasons..) and episode ratings are not being grabbed at all for the show. The ratings for this show should be grabbed from http://www.imdb.com/title/tt5031234/

- Episode's keep returning a N/A rating on any episode for every show even though they are rated on IMDB.

**Comment by campanflaviu** [comment]
I'll look into this tv show and how can I improve the search. It's strange that you are getting ratings for seasons, It's not showing for me. Anyway, I'll make sure no imdb ratings will be shown for seasons.

I noticed also that for newer episodes there isn't any IMDB rating provided or some are outdated. This is because IMDB doesn't have an open api. Right now I'm using [http://omdbapi.com/](http://omdbapi.com/) which is cool because it doesn't require an api key, but the downside is that it's not updated that often.
Also, Plex doesn't return an IMDB id as it does for movies which will result in an exact match. For Plex servers that don't have the IMDB linked and for tv shows it performs a search by title and year.

**Comment by JourneyOver** [comment]
Issue for the first point seems to be fixed now as the show is now at least pointing to the correct IMDB. Ratings disappeared from the seasons section so that's good, episode rating is broken for the show (it's only happening on Time after Time (2017) ) though as the episodes don't give any sorta rating thing still no N/A or anything.

Ah I see must be a long time before they decide to update it as I still have a couple shows that have episodes from 2016 that still end up showing a N/A rating..

**Comment by campanflaviu** [comment]
Episodes for Time after Time (2017) look fine to me, and even for the first two episodes I get the ratings, the second one being released 9 days ago. Maybe a refresh would fix this?
However I also noticed that there are many new episodes which are getting N/A ratings. In that case I will disable episode rating for now. Maybe until I find a better api.

**Comment by JourneyOver** [comment]
See you added trakt ratings into the mix now which is great :D dunno if it's working fully or not though as it's only showing up for Movies and the tv show, doesn't show up for seasons and episodes any (which both have their own ratings apart from the actual show ratings). (and I have refreshed the page multiple times)

I do seem to get this error whenever I enter a season or episode page, doesn't happen when I enter a show or movie page so thinking this has something to do with it possibly..
```
Uncaught TypeError: Cannot read property 'imdb_id' of undefined
    at Object.processResource (omdb.js:32)
    at content.js:65
    at XMLHttpRequest.xhr.onload (helpers.js:48)
processResource @ omdb.js:32
(anonymous) @ content.js:65
xhr.onload @ helpers.js:48
```

**Comment by campanflaviu** [comment]
I'm going to use more from the Trakt API like trailers and missing episodes. As for season and episode Trakt rating, I think it will be addressed later since retrieving correct data for them is a little bit trickier (that's why I also removed ratings for IMDB episode ratings). I'll look into fixing this error though. 
Thanks!

**Comment by campanflaviu** [comment]
I'm going to close this issue since it's solved and so it won't be too cluttered. Please feel free to open a new issue if you find any bugs / have suggestions.
