### ISSUE TITLE
app.plex.tv - Not working

### ISSUE THREAD

**Issue by KurtzPT** [campanflaviu/plexius#6]
I'm not sure if I'm missing something but going to app.plex.tv and looking around it seems the plugin is not working, no imdb, no missing seasons feature, nothing works.

I've installed the latest version on chrome.

**Comment by campanflaviu** [comment]
This might be cause by this issue https://github.com/campanflaviu/plexius/issues/7 . Hopefully it can be solved

**Comment by KurtzPT** [comment]
It's still not working very well, sometimes it loads up, other times it doesn't.

**Comment by campanflaviu** [comment]
Yes, I'm aware about this issue. Unfortunately is because plex web element classes are being changed over a couple of releases and this extension relies on those classes to know where to inject the ratings and the other features. I'm working on a solution that hopefully won't be affected by those changes in the future.
